name: getx_skeleton
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5 # for state managment and context less stuff

  logger: ^1.1.0 # log events in clear way insted of (print)

  flutter_screenutil: ^5.4.0 # make app responsive

  dio: ^4.0.6 # for api requests

  hive: ^2.2.1 # local database (SQFlite replacement)
  hive_flutter: ^1.1.0 # make it easy to use hive (no need for path provider)
  get_storage: ^2.0.3 # shared preferences replacement (sync)

  firebase_core: ^1.17.1 # to initialize firebase services
  firebase_messaging: ^11.4.1 # fcm services
  awesome_notifications: ^0.6.21 # notifications services (will be used for fcm)

  flutter_launcher_icons: ^0.9.3 # change app icon
  change_app_package_name: ^1.1.0 # change package name
  rename_app: ^1.1.0 # rename app
  flutter_tree: ^2.0.3
  file_picker:



  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  build_runner: ^2.1.11 # generate dart files
  hive_generator: ^1.1.3 # generate hive files

  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900

